name: actions
on:
  pull_request:
  push:
    branches: main

jobs:
  runsJest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run test

      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge

  automerge:
    runs-on: ubuntu-latest
    needs: runsJest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000
